# Generated by Django 4.1.7 on 2023-03-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Not allowed to tweet'), (2, 'Allowed to tweet')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweeted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
