# Generated by Django 4.1.7 on 2023-03-20 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autotweeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='status',
            field=models.IntegerField(choices=[(0, 'For Review'), (1, 'Not allowed to tweet'), (2, 'Allowed to tweet')], default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweeted_at',
            field=models.DateTimeField(default=None, help_text='A non-empty value in this field indicates that the tweet has been sent out.', null=True),
        ),
    ]
